name: Sphinx Make HTML
run-name: ${{ github.actor }} is building the HTML
on: [push]
jobs:
  Install-Compile-Commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - run: |
            pip install sphinx
            pip install sphinx-book-theme
            pip install sphinxcontrib-drawio
            make html
            
        - name: Commit files
          run: |
            git config --local user.name actions-user
            git config --local user.email "actions@github.com"
            if ! git diff --exit-code; then
                git add -A
                git commit -am "Automatic sphinx compiling added $(date)"
                git push -f origin main
            fi
