name: Sphinx Make HTML
run-name: ${{ github.actor }} is building the HTML
on: push
jobs:
  Install-Compile-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sudo chmod -R 777 /run/user/1001
          sudo snap install drawio
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install Sphinx and Packages
        run: |
          pip install sphinx
          pip install sphinx-book-theme
          pip install sphinxcontrib-drawio
      - name: Build HTML
        run: make html
            
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
              git add -A
              git commit -am "Automatic Sphinx build on $(date)"
              git push -f origin main
          fi
      - name: Install Latex
        run: |
          sudo apt-get install -y latexmk
      
      - name: Build PDF
        run: make latexpdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: _build/latex/geometry-notes.pdf
